### ISSUE TITLE
For Loop Error in mut_matrix()

### ISSUE THREAD

**Issue by liggettla** [UMCUGenetics/MutationalPatterns#11]
I have run through the Bioconductor vignettes with no issues, and have started using some of my own sample vcf files. So far, everything has worked fine with my own vcf files, but when I try to create the 96 mutation profile using `mut_matrix()`  using the same call from the manual: `mut_mat <- mut_matrix(vcf_list = vcfs, ref_genome = ref_genome)` I get the following error: `Error in for (vcf in vcf_list) { : invalid for() loop sequence`.

I have played with input sample numbers and content, but still continue to get this error.

**Comment by roelj** [comment]
Hello @liggettla.  Thanks for reporting this issue.

We have already implemented a fix, which will be available in a week or so in the next Bioconductor release.

Alternatively, you could choose to:
- Make a `list` instead of a `GRangesList` from your input data (Do so by surrounding `list(...)` on the vcfs parameter: `list(vcfs)`.)
- Or use the code from the Github page.  Do so by running:
```{r}
library(devtools)
install_github("UMCUgenetics/MutationalPatterns")
```
Choosing the second option will be a more pleasant transition to the next Bioconductor release's version, as it contains all the latest changes.

Please let me know whether either solution works for you, and if not, what problem you run into, so I can look at a further fix.

Thanks!

**Comment by liggettla** [comment]
@roelj Thanks for the suggestions, I did try converting vcfs to a list but I still get an error: `Error in combine_CompressedList_objects(class(x), objects, use.names = FALSE, : the objects to combine must be CompressedList objects (or NULLs)`

When using the most recent code from github, the problem is fixed, and the call works as expected.

Unrelated, one change I needed after using the version on github, is to use the full genome name as `hg19` was not recognized when making this call `vcfs <- read_vcfs_as_granges(vcf_files, sample_names, genome = "BSgenome.Hsapiens.UCSC.hg19")` (I assume you already know about this though).

**Comment by roelj** [comment]
Hi @liggettla.  Thanks for the quick response.  Yes, we are aware of this.  We did this to solve a whole range of problems later on in the use of the package.

I'm glad you've got it working now.  It's only waiting for the next Bioconductor release to have these bugfixes in, so I consider this solved.

Thanks for reporting.
